<?php

return array(
    //code  =>  'mage name      Width   Height  Alt    
    '3:)'   =>  array('sm_devil', '15',   '15',   'devil'),
    '3:-)'   =>  array('sm_devil', '15',   '15',   'devil'),
    '3:=)'   =>  array('sm_devil', '15',   '15',   'devil'),
    ':v'   =>  array('sm_pacman', '15',   '15',   'pacman'),
    ':V'   =>  array('sm_pacman', '15',   '15',   'pacman'),
    ':-)'   =>  array('sm_smile', '15',   '15',   'happy'),
    '</3'   =>  array('sm_bheart', '15',   '15',   'heart broken'),
    '<\\3'   =>  array('sm_bheart', '15',   '15',   'heart broken'),
    '/l'   =>  array('sm_bheart', '15',   '15',   'heart broken'),
    '/L'   =>  array('sm_bheart', '15',   '15',   'heart broken'),
    /* '(nocath)'   =>  array('sm_bheart', '15',   '15',   'heart broken'),*/
    ':]'   =>  array('sm_smile', '15',   '15',   'happy'),
    '=)'   =>  array('sm_smile', '15',   '15',   'happy'),
    '^_^'   =>  array('sm_smile2', '15',   '15',   'happy'),
    '^^'   =>  array('sm_smile2', '15',   '15',   'happy'),
    '>:('   =>  array('sm_grumpy', '15',   '15',   'grumpy'),   
    '><'   =>  array('sm_grumpy', '15',   '15',   'grumpy'),
    '>:-('   =>  array('sm_grumpy', '15',   '15',   'grumpy'),
    '>=('   =>  array('sm_grumpy', '15',   '15',   'grumpy'),
    '-_-'   =>  array('sm_squint', '15',   '15',   'squint'),  
    '(kolab)'   =>  array('sm_kolab', '15',   '15',   'kolab'),
    ':))'   =>  array('21.gif', '15',   '15',   'laughing'),
    ':)'    =>  array('sm_smile',  '15',   '15',   'happy'),
    ':(('   =>  array('20.gif', '22',   '15',   'crying'),
    ':('    =>  array('sm_sad',  '15',   '15',   'sad'),
    ':['    =>  array('sm_sad',  '15',   '15',   'sad'),
    ':-('    =>  array('sm_sad',  '15',   '15',   'sad'),
    '=('    =>  array('sm_sad',  '15',   '15',   'sad'),    
    ':-/'    =>  array('sm_unsure2',  '15',   '15',   'unsure'),
    ':/'    =>  array('sm_unsure2',  '15',   '15',   'unsure'),
     '=/'    =>  array('sm_unsure2',  '15',   '15',   'unsure'),
    ':\\'    =>  array('sm_unsure2',  '15',   '15',   'unsure'),
    '=\\'    =>  array('sm_unsure2',  '15',   '15',   'unsure'),
    ':-\\'    =>  array('sm_unsure2',  '15',   '15',   'unsure'),
    'o.O'    =>  array('sm_wut',  '15',   '15',   'oops'),
    'O.o'    =>  array('sm_wut',  '15',   '15',   'oops'),
    'o.0'    =>  array('sm_wut',  '15',   '15',   'oops'),
    '0.o'    =>  array('sm_wut',  '15',   '15',   'oops'),
    ':|'    =>  array('sm_wut',  '15',   '15',   'oops'),
    '=|'    =>  array('sm_wut',  '15',   '15',   'oops'),
    '(o)'    =>  array('sm_pacball',  '15',   '15',   'pacball'),
    '(O)'    =>  array('sm_pacball',  '15',   '15',   'pacball'),
    ':-P'    =>  array('sm_tongue',  '15',   '15',   'tongue'),
    ':-p'    =>  array('sm_tongue',  '15',   '15',   'tongue'),
    '=P'    =>  array('sm_tongue',  '15',   '15',   ''),
    ':w1'    =>  array('sm_pacghost1',  '15',   '15',   ''),
    ':w2'    =>  array('sm_pacghost2',  '15',   '15',   ''),
    ':w3'    =>  array('sm_pacghost3',  '15',   '15',   ''),
    ':w4'    =>  array('sm_pacghost4',  '15',   '15',   ''),
    ':W1'    =>  array('sm_pacghost1',  '15',   '15',   ''),
    ':W2'    =>  array('sm_pacghost2',  '15',   '15',   ''),
    ':W3'    =>  array('sm_pacghost3',  '15',   '15',   ''),
    ':W4'    =>  array('sm_pacghost4',  '15',   '15',   ''),
    '>:O'    =>  array('sm_wtf',  '15',   '15',   ''),
    '>:o'    =>  array('sm_wtf',  '15',   '15',   ''),
    '>:-O'    =>  array('sm_wtf',  '15',   '15',   ''),
    '>:-o'    =>  array('sm_wtf',  '15',   '15',   ''),
    '>:=O'    =>  array('sm_wtf',  '15',   '15',   ''),
    '>:=o'    =>  array('sm_wtf',  '15',   '15',   ''),
    ':-O'    =>  array('sm_oh',  '15',   '15',   ''),
    ':O'    =>  array('sm_oh',  '15',   '15',   ''),
    ':-o'    =>  array('sm_oh',  '15',   '15',   ''),
    ':o'    =>  array('sm_oh',  '15',   '15',   ''),
    '=o'    =>  array('sm_oh',  '15',   '15',   ''),
    '=O'    =>  array('sm_oh',  '15',   '15',   ''),
    ':3'    =>  array('sm_balls',  '15',   '15',   ''),
    ':-3'    =>  array('sm_balls',  '15',   '15',   ''),
    '=3'    =>  array('sm_balls',  '15',   '15',   ''),
    '(nxe)'    =>  array('ic_nxe.png',  '15',   '15',   'nxe'),
    ":'("    =>  array('sm_cry',  '15',   '15',   'cry'),
    "='("    =>  array('sm_cry',  '15',   '15',   'cry'),
    ":,("    =>  array('sm_cry',  '15',   '15',   'cry'),
    "=,("    =>  array('sm_cry',  '15',   '15',   'cry'),
    "t_t"    =>  array('sm_cry',  '15',   '15',   'cry'),
    "T_T"    =>  array('sm_cry',  '15',   '15',   'cry'),
    ';)'    =>  array('sm_wink',  '15',   '15',   'winking'),
    ';]'    =>  array('sm_wink',  '15',   '15',   'winking'),
    ';-)'    =>  array('sm_wink',  '15',   '15',   'winking'), 
    ';D'    =>  array('sm_bsmile2',  '15',   '15',   'big grin'),
    ';-D'    =>  array('sm_bsmile2',  '15',   '15',   'big grin'),
    ':D'    =>  array('sm_bsmile',  '15',   '15',   'big grin'),
    ':-D'    =>  array('sm_bsmile',  '15',   '15',   'big grin'),
    '=D'    =>  array('sm_bsmile',  '15',   '15',   'big grin'),
    '<3'    =>  array('sm_heart',  '15',   '15',   'love'),
    '(L)'    =>  array('sm_heart',  '15',   '15',   'love'),
    '(l)'    =>  array('sm_heart',  '15',   '15',   'love'),
   /* '(cath)'    =>  array('sm_heart',  '15',   '15',   'love'),*/
    '(rosenda)'    =>  array('sm_rosenda',  '15',   '15',   'rosenda'),
     '(john)'    =>  array('sm_john',  '15',   '15',   'john'),
    ':p'    =>  array('sm_tongue', '15',   '15',   'tongue'),
    ':P'    =>  array('sm_tongue', '15',   '15',   'tongue'),
    ':*'    =>  array('sm_kiss', '15',   '15',   'kiss'),
    '=*'    =>  array('sm_kiss', '15',   '15',   'kiss'),
    ':-*'    =>  array('sm_kiss', '15',   '15',   'kiss'),
    ':s'    =>  array('sm_unsure', '15',   '15',   ''),
    ':S'    =>  array('sm_unsure', '15',   '15',   ''), 
    ':-s'    =>  array('sm_unsure', '15',   '15',   ''),
    ':-S'    =>  array('sm_unsure', '15',   '15',   ''), 
    '=s'    =>  array('sm_unsure', '15',   '15',   ''),
    '=S'    =>  array('sm_unsure', '15',   '15',   ''), 
    'O:-)'  =>  array('sm_angel',  '30',   '15',   'angel'),
    'o:-)'  =>  array('sm_angel',  '30',   '15',   'angel'),
    'O:=)'  =>  array('sm_angel',  '30',   '15',   'angel'),
    'o:=)'  =>  array('sm_angel',  '30',   '15',   'angel'),
    'O:)'  =>  array('sm_angel',  '30',   '15',   'angel'),
    'o:)'  =>  array('sm_angel',  '30',   '15',   'angel'),
    '(a)'  =>  array('sm_angel',  '30',   '15',   'angel'),
    ':-B'   =>  array('sm_glass',  '15',   '15',   'nerd'),
    '8)'   =>  array('sm_glass',  '15',   '15',   'nerd'),
    'B)'   =>  array('sm_glass',  '24',   '15',   'nerd'),
    ':B'   =>  array('sm_glass',  '24',   '15',   'nerd'),
    '8-)'   =>  array('sm_glass',  '24',   '15',   'nerd'),
    'B-)'   =>  array('sm_glass',  '24',   '15',   'nerd'),   
    '8-|'   =>  array('sm_cool',  '15',   '15',   'rolling eyes'),
    'B-|'   =>  array('sm_cool',  '15',   '15',   'rolling eyes'),
    '8|'   =>  array('sm_cool',  '15',   '15',   'rolling eyes'),
    'B|'   =>  array('sm_cool',  '15',   '15',   'rolling eyes'), 
    '(H)'   =>  array('sm_cool',  '15',   '15',   'rolling eyes'), 
    'D:'    =>  array('sm_damn',  '15',   '15',   ''),
    'D:-'    =>  array('sm_damn',  '15',   '15',   ''),
    'D='    =>  array('sm_damn',  '15',   '15',   ''),
    ':@'    =>  array('sm_angry',  '15',   '15',   ''),
    ':-@'    =>  array('sm_angry',  '15',   '15',   ''),
    '=@'    =>  array('sm_angry',  '15',   '15',   ''),
    '(K)'    =>  array('sm_cactus',  '15',   '15',   ''),
    '(k)'    =>  array('sm_cactus',  '15',   '15',   ''),
    '(zzz)'    =>  array('sm_sleepy',  '15',   '15',   ''),
    '(zz)'    =>  array('sm_sleepy',  '15',   '15',   ''),
    'Zzz'    =>  array('sm_sleepy',  '15',   '15',   ''),
    'x_x'   =>  array('sm_sick', '15',   '15',   'happy'),
    'X_X'   =>  array('sm_sick', '15',   '15',   'happy'),
    'x-x'   =>  array('sm_sick', '15',   '15',   'happy'),
    'X-X'   =>  array('sm_sick', '15',   '15',   'happy'),
    ':$'   =>  array('sm_shy', '15',   '15',   'happy'),
    '(shy)'   =>  array('sm_shy', '15',   '15',   'happy'),
    '(eat)'   =>  array('sm_burger', '15',   '15',   'happy'),
    '(burger)'   =>  array('sm_burger', '15',   '15',   'happy'),
    '(applesuck)'   =>  array('sm_as', '15',   '15',   'happy'),
);